version: '3.1'

services:

  wordpress:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: vuna2004/wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - ./local/wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./local/db:/var/lib/mysql

volumes:
  wordpress:
  db:
